  
name: LateX
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    #- name: Compile Notes
    #  uses: xu-cheng/latex-action@master
    #  with:
    #    root_file: notes/math/linear/main.tex
    #- name: Check pdf files
    #  run: |
    #    file main.pdf | grep -q ' PDF '
    - name: Upload
      run: |
        # configure git
        git config --global user.name "HarryWangATX"
        git config --global user.email "harrynicomama@gmail.com"
        # setup ssh


        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

       

        ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -T git@github.com -v
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 --branch gh-pages git@github.com:WHS-Resources/WHS-Resources.git "$GITHUB_WORKSPACE/deploy"
        cp -f main.pdf "$GITHUB_WORKSPACE/deploy/main.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add main.pdf
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
