name: Build LaTeX document
on: [push]
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v1
            - uses: xu-cheng/latex-action@v2
              with:
                  root_file: |
                      notes/math/linear/main.tex
